name: sandbox
channels:
  - bioconda
  - biobuilds
  - defaults
dependencies:
  - bcftools
  - bedtools
  - bowtie2
  - fastqc
  - htslib
  - krona
  - kraken2
  - minimap2
  - medaka
  - pip
  - samtools
  - trimmomatic
  - pip:
    - nanoplot